{{- if .Values.persistence.pv.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pv.name | quote }}
spec:
  capacity:
    storage: {{ .Values.persistence.pv.capacity | quote }}
  accessModes:
    - {{ .Values.persistence.pv.accessMode | quote }}
  cephfs:
    monitors:
    - {{ .Values.persistence.pv.monitor }}
    secretRef:
      name: {{ .Values.persistence.pv.secretName }}
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvc.name | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.pv.accessMode | quote }}
  dataSource: null
  resources:
    requests:
      storage: {{ .Values.persistence.pv.capacity | quote }}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.pv.name | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.persistence.pv.secretName }}
type: Opaque
stringData:
  config.yaml: |-
    {{ .Values.persistence.pv.secretKey }}: {{ .Values.persistence.pv.secretValue | quote }}
{{- end }}
