# Default values for superset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pietrocannalire/superset
  tag: latest
  pullPolicy: Always

namespace: default

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "superset"

service:
  type: ClusterIP
  port: 8088

env:
  cacheEnabled: filesystem
  supersetUser:
  supersetPassword:
  supersetEmail:
  supersetFirstName:
  supersetLastName:
  
  logoutRedirectUrl:
  shibHeaders:
  supersetConfigPath:
  sqlAlchemyMetadataUri:
  sqlAlchemyDataUri:
  loadExamples:

ingress: 
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: superset.default.sdp.csi.it
  tls: false

persistence:
  pv:
    enabled: false
    name: pv-superset
    accessMode: "ReadWriteMany"
    capacity: "1Gi"
    monitor: 10.102.190.74:6789
    secretName: secret-cephfs
    secretKey: client.admin
    secretValue: AQDmlwNdCzq4LhAA7kut8yMEadQl6EPWiHRAwg==
  pvc:
    name: pvc-superset
    volName: superset-data
    mountPath: /var/lib/superset
    subPath: superset-subpath1

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
   limits:
  #   cpu: 100m
     memory: 500Mi
   requests:
     cpu: 250m
     memory: 250Mi

livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

nodeSelector: {}

tolerations: []

affinity: {}
